### ISSUE TITLE
cannot install with python-36-rhel7

### ISSUE THREAD

**Issue by aradzhabov** [ing-bank/sparse_dot_topn#32]
Thank you for the great lib!!
It works perfect for the most environments I tried it.
But I a little stuck with our internal network environment.
You cannot go to the internet from the environment.
The internal network has local mirror of https://pypi.org/
And I can use only 1 base image in docker file: python-36-rhel7
python-36-rhel7 does not have inside numpy and Cython but I can get ones from local mirror.
Since numpy and Cython must be availabel in environment before import you lib
I created two requirements files .. and my docker file looks like
.....
RUN pip install --trusted-host {our local mirror of pypi} -r requirements_INSTALL ME FIRST.txt
RUN pip install --trusted-host {our local mirror of pypi} -r requirements.txt
....
requirements_INSTALL ME FIRST.txt
has only two lines:
numpy
Cython

requirements.txt has libs i need for my app including yours
......
scipy
sparse_dot_topn
.......

But I am getting the following error during processing docker file..
may be you could suggest something  .. I do understand that there is a chance that it is not problem of your lib .. may be some compilers must be added as dependencies or may be there is way to avoid compiling sources of your lib ... sorry if my explanation a bit unprofessional. here is the log:
Sending build context to Docker daemon    20 MB

Step 1/14 : FROM registry.sigma.sbrf.ru/base/rhscl/python-36-rhel7:latest
 ---> b9308e79e7c4
Step 2/14 : RUN mkdir -p /home/project/app
 ---> Using cache
 ---> c6b5d53f6613
Step 3/14 : RUN mkdir -p /home/project/app/models
 ---> Using cache
 ---> 49dfc5996aac
Step 4/14 : WORKDIR /home/project/app
 ---> Using cache
 ---> d97c2a88fa4a
Step 5/14 : USER root
 ---> Using cache
 ---> a1e97cc58d7a
Step 6/14 : COPY requirements_INSTALL_ME_FIRST.txt /home/project/app
 ---> Using cache
 ---> 2aab9acb3938
Step 7/14 : COPY requirements.txt /home/project/app
 ---> Using cache
 ---> 055d12208f36
Step 8/14 : RUN pip install -i http://mirror.sigma.sbrf.ru/pypi/simple/ --trusted-host mirror.sigma.sbrf.ru --no-cache-dir --upgrade pip
 ---> Running in e5329bff554a
[91m[0m
Collecting pip
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/54/2e/df11ea7e23e7e761d484ed3740285a34e38548cf2bad2bed3dd5768ec8b9/pip-20.1-py2.py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-20.1
 ---> f3eb17ead1fe
Removing intermediate container e5329bff554a
Step 9/14 : RUN pip install -i http://mirror.sigma.sbrf.ru/pypi/simple/ --trusted-host mirror.sigma.sbrf.ru --no-cache-dir -r requirements_INSTALL_ME_FIRST.txt
 ---> Running in b99043a0f5d6

[91m[0mLooking in indexes: http://mirror.sigma.sbrf.ru/pypi/simple/
Collecting numpy
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/3d/fc/4763e5f17ac6e7e7d55f377cde859ca1c5d5ac624441ab45315bc578aa9e/numpy-1.18.3-cp36-cp36m-manylinux1_x86_64.whl (20.2 MB)
Collecting Cython
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/e7/d7/510ddef0248f3e1e91f9cc7e31c0f35f8954d0af92c5c3fd4c853e859ebe/Cython-0.29.17-cp36-cp36m-manylinux1_x86_64.whl (2.1 MB)
Installing collected packages: numpy, Cython
Successfully installed Cython-0.29.17 numpy-1.18.3
 ---> dbe6764e12cc
Removing intermediate container b99043a0f5d6
Step 10/14 : RUN pip install -i http://mirror.sigma.sbrf.ru/pypi/simple/ --trusted-host mirror.sigma.sbrf.ru --no-cache-dir -r requirements.txt
 ---> Running in f0afbcce158e

[91m[0mLooking in indexes: http://mirror.sigma.sbrf.ru/pypi/simple/
Collecting Flask==1.0.2
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl (91 kB)
Collecting Flask-Cors==3.0.7
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/65/cb/683f71ff8daa3aea0a5cbb276074de39f9ab66d3fbb8ad5efb5bb83e90d2/Flask_Cors-3.0.7-py2.py3-none-any.whl (13 kB)
Collecting requests==2.21.0
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57 kB)
Collecting gunicorn
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
Collecting cloudpickle
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/c6/a5/bb99276ec2685e11d34e4aefc0d9238626843ea51f974aa59c68317d34b2/cloudpickle-1.4.1-py3-none-any.whl (26 kB)
Collecting sklearn
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz (1.1 kB)
Collecting pandas==0.23.4
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/e1/d8/feeb346d41f181e83fba45224ab14a8d8af019b48af742e047f3845d8cff/pandas-0.23.4-cp36-cp36m-manylinux1_x86_64.whl (8.9 MB)
Collecting python-decouple
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/c7/82/dd20cdca396f58be86c6e710a3958f4a34ca98c5dd3989ee978b6cb9f97e/python-decouple-3.3.tar.gz (10 kB)
Collecting flask-swagger
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/b2/a9/a6c05fbc592ac482bf9557e47957c429d2be8cb8addfbc92853fb862ea8f/flask-swagger-0.2.14.tar.gz (8.6 kB)
Collecting pymorphy2
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/a3/33/fff9675c68b5f6c63ec8c6e6ff57827dda28a1fa5b2c2d727dffff92dd47/pymorphy2-0.8-py2.py3-none-any.whl (46 kB)
Collecting scipy
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/dc/29/162476fd44203116e7980cfbd9352eef9db37c49445d1fec35509022f6aa/scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (26.1 MB)
Collecting sparse_dot_topn
  Downloading http://mirror.sigma.sbrf.ru/pypi/packages/70/d5/2a3a52acd89344f0c45cae320bd41ee49573caec656834b98c5ea48669b7/sparse_dot_topn-0.2.9.tar.gz (106 kB)
[91m    ERROR: Command errored out with exit status 1:
     command: /opt/app-root/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2mn7oykc/sparse-dot-topn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2mn7oykc/sparse-dot-topn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6hddfot_
         cwd: /tmp/pip-install-2mn7oykc/sparse-dot-topn/
    Complete output (198 lines):
    /tmp/easy_install-dfl3_1l3/scipy-1.4.1/setup.py:420: UserWarning: Unrecognized setuptools command ('-q bdist_egg --dist-dir /tmp/easy_install-dfl3_1l3/scipy-1.4.1/egg-dist-tmp-auf8o3r8'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Traceback (most recent call last):
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 964, in send
        self.connect()
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/ssl_support.py", line 190, in connect
        sock, cert_reqs=ssl.CERT_REQUIRED, ca_certs=self.ca_bundle
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 1149, in wrap_socket
        ciphers=ciphers)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 814, in __init__
        self.do_handshake()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 1068, in do_handshake
        self._sslobj.do_handshake()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 747, in open_url
        return open_with_auth(url, self.opener)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 948, in _socket_timeout
        return func(*args, **kwargs)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 1067, in open_with_auth
        fp = opener(request)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/ssl_support.py", line 161, in https_open
        lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-dfl3_1l3/scipy-1.4.1/setup.py", line 540, in <module>
      File "/tmp/easy_install-dfl3_1l3/scipy-1.4.1/setup.py", line 536, in setup_package
      File "/opt/app-root/lib/python3.6/site-packages/numpy/distutils/core.py", line 128, in setup
        dist = setup(**new_attr)
      File "/opt/app-root/lib/python3.6/site-packages/numpy/distutils/core.py", line 171, in setup
        return old_setup(**new_attr)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/app-root/lib/python3.6/site-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
        Distribution.__init__(self, attrs)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 653, in easy_install
        not self.always_copy, self.local_index
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 636, in fetch_distribution
        dist = find(requirement)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 617, in find
        dist.download_location = self.download(dist.location, tmpdir)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 566, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 805, in _download_url
        return self._attempt_download(url, filename)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 811, in _attempt_download
        headers = self._download_to(url, filename)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 710, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 761, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/56/cf/efb853937e69168a215a70c049b66b2e8aea3b9a1929f9650752d7ff1f32/pybind11-2.5.0.tar.gz#sha256=ea5a4e7a880112915463826f1acbec5892df36dfe102ecb249229ac514fb54ad: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2mn7oykc/sparse-dot-topn/setup.py", line 75, in <module>
        ext_modules=[original_ext, threaded_ext],
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup
        raise
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-dfl3_1l3/scipy-1.4.1/setup.py", line 540, in <module>
      File "/tmp/easy_install-dfl3_1l3/scipy-1.4.1/setup.py", line 536, in setup_package
      File "/opt/app-root/lib/python3.6/site-packages/numpy/distutils/core.py", line 128, in setup
        dist = setup(**new_attr)
      File "/opt/app-root/lib/python3.6/site-packages/numpy/distutils/core.py", line 171, in setup
        return old_setup(**new_attr)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/app-root/lib/python3.6/site-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
        Distribution.__init__(self, attrs)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 653, in easy_install
        not self.always_copy, self.local_index
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 636, in fetch_distribution
        dist = find(requirement)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 617, in find
        dist.download_location = self.download(dist.location, tmpdir)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 566, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 805, in _download_url
        return self._attempt_download(url, filename)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 811, in _attempt_download
        headers = self._download_to(url, filename)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 710, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/package_index.py", line 761, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/56/cf/efb853937e69168a215a70c049b66b2e8aea3b9a1929f9650752d7ff1f32/pybind11-2.5.0.tar.gz#sha256=ea5a4e7a880112915463826f1acbec5892df36dfe102ecb249229ac514fb54ad: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[0m

**Comment by aradzhabov** [comment]
on Monday I will try to add pip install ..... setuptools --upgrade
hope it helps

**Comment by aradzhabov** [comment]
pip install setuptools --upgrade
- helped to resolve my problem
