### ISSUE TITLE
Compatibility with Apple Chip

### ISSUE THREAD

**Issue by paynejason** [ing-bank/sparse_dot_topn#74]
My team has just switched from Intel cores to new computers with Apple M1 Chips and we are now receiving errors from sparse_dot_topn. The code still works on the old computers running the same operating system (macOS Monterey), but running the same source code with the same software versions gets us the error below:

Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/text2term/__main__.py", line 4, in <module>
    from t2t import Text2Term
  File "/app/text2term/t2t.py", line 12, in <module>
    from tfidf_mapper import TFIDFMapper
  File "/app/text2term/tfidf_mapper.py", line 5, in <module>
    import sparse_dot_topn as ct
  File "/usr/local/lib/python3.9/site-packages/sparse_dot_topn/__init__.py", line 5, in <module>
    from sparse_dot_topn.awesome_cossim_topn import awesome_cossim_topn
  File "/usr/local/lib/python3.9/site-packages/sparse_dot_topn/awesome_cossim_topn.py", line 7, in <module>
    from sparse_dot_topn import sparse_dot_topn as ct
  File "sparse_dot_topn/sparse_dot_topn.pyx", line 29, in init sparse_dot_topn.sparse_dot_topn
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

Is this repository compatible with new cores? Or is there another issue we should look for?

**Comment by luizvbo** [comment]
Hi Jason,

I have a Macbook with M1 and I managed to reproduce the example from the README file. Are you using the last version of the package? What versions of the numpy, scipy and Cython do you have in your system?

My environment:
```
numpy                         1.22.4
scipy                         1.8.1
Cython                        0.29.32
sparse-dot-topn               0.3.3
```

**Comment by paynejason** [comment]
Hi Luiz,

Thanks for the response. We were actually able to resolve the problem by changing our requirements.txt to this:
```
Owlready2==0.36
argparse==1.4.0
pandas==1.4.1
numpy==1.23.2
gensim==4.1.2
scipy==1.8.0
scikit-learn==1.0.2
setuptools==60.9.3
requests==2.27.1
tqdm==4.62.3
sparse_dot_topn==0.3.1
bioregistry==0.4.63
nltk==3.7
rapidfuzz==2.0.5
shortuuid==1.0.9
```

It is worth noting that when we tried to use sparse-dot-topn v0.3.3 that the build failed, saying only up to v0.3.1 existed in pip, despite v0.3.3 being published on PyPI. We believe the hardcoded numpy==1.23.2 is what solved the issue.
